### ISSUE TITLE
Various things

### ISSUE THREAD

**Issue by davelab6** [shinntype/bellefair#3]
- [x] The 1.png in the root is blank. What was it meant to be? Removed in #2
- [x] I'll renamed the files and directories - fixed in #2
- [x] The description in the README is very minimal, please write a more descriptive description of the design, the rationale, the future of the project. I’ll use this text on the www.google.com/fonts directory :) 
- [x] Inside the TTF file’s `name` table, the copyright notice is missing. It should be
  
  Copyright 2015 The Bellefair Project Authors.

fixed in #2
- [x] And then 2 other files are added to define what that means, AUTHORS.txt and CONTRIBUTORS.txt  - fixed in #2
- [x] The unique ID was
  
  \byNickShinn: Bellefair: 2015

It should be

```
1.001: Bellefair: 2015
```

fixed in #2
- [x] The version was 
  
  Version 001.000

it should be 

```
Version 1.001
```

fixed in #2
- [x] The PostScript name was
  
  Bellefair

it should be

```
Bellefair-Regular
```

fixed in #2
- [x] The designers field was
  
  Nick Shinn

it should be

```
Nick Shinn, Liron Lavi Turkenich
```

fixed in #2
- [x] The license and licenseURL fields were not set, they should be
  
  This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL

and

```
http://scripts.sil.org/OFL
```

fixed in #2

**Comment by lironlavitur** [comment]
Hi Dave!

How are you?

Just making sure- you sent those as updates right? I have nothing further
to do?

I saw that the new google fonts are up on the new website (NICE website)
but didn't see Bellefair there.
Do you know why?

I'm asking because there's a buzz in Israel about those new fonts and I
would hate to see Bellefair go out of the radar.

Have a lovely day,
Liron

On Mon, May 23, 2016 at 5:25 PM, Dave Crossland notifications@github.com
wrote:

> Closed #3 https://github.com/shinntype/bellefair/issues/3.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/shinntype/bellefair/issues/3#event-669024922

## 

Liron Lavi Turkenich
Type & Graphic Design, Research

+972-544872265
www.lironlavi.com
@LironLaviTur https://twitter.com/LironLaviTur
Aravrit https://www.facebook.com/aravrit?ref=aymt_homepage_panel, one
script, two languages

**Comment by davelab6** [comment]
Yes, I'm sorry that this didn't make it; there will be another round of
releases - with more scripts - in the next few weeks :)

**Comment by nickshinn** [comment]
On the upside, the next (press) release will be about the fonts, not the site!

I would like to think Bellefair will get some serious consideration in the design community, on account of the theory behind it (as well as the execution!) I will certainly give it hype.

I think too that the huge challenge of adding Hebrew to an ultra-latin design with a tiny x-height is quite a story. 

Don’t you find the figures rather overpowering for the Hebrew Liron? I had my doubts at first for the Latin, but tried various treatments in both old style figures and three-quarter height lining as well, and was rather surprised to discover that this style of “floating" (rather than standing) cap-height figure was the best design solution.

Cheers,

Nick

**Comment by lironlavitur** [comment]
No worries Dave, it will be great whenever it comes out.

Nick, I must agree with you and I had some thoughts about this issue and I
diminished them quickly because I didn't think it's an option. I do know
that it's possible and I think that the Hebrew should get new figures. The
Latin original ones will remain, but while setting the Hebrew it makes
sense to get a different set of figures as the default. I think the Hebrew
figures should be much shorter and a bit heavier.
Dave, what do you think? Too late to change now? When is the second batch
due?

Have a good night,
Liron

On Wed, Jun 15, 2016 at 6:00 PM, Nick Shinn notifications@github.com
wrote:

> On the upside, the next (press) release will be about the fonts, not the
> site!
> 
> I would like to think Bellefair will get some serious consideration in the
> design community, on account of the theory behind it (as well as the
> execution!) I will certainly give it hype.
> 
> I think too that the huge challenge of adding Hebrew to an ultra-latin
> design with a tiny x-height is quite a story.
> 
> Don’t you find the figures rather overpowering for the Hebrew Liron? I had
> my doubts at first for the Latin, but tried various treatments in both old
> style figures and three-quarter height lining as well, and was rather
> surprised to discover that this style of “floating" (rather than standing)
> cap-height figure was the best design solution.
> 
> Cheers,
> 
> Nick
> 
> Sent from my iPhone
> 
> > On Jun 15, 2016, at 3:59 AM, Liron Lavi Turkenich <
> > notifications@github.com> wrote:
> > 
> > Hi Dave!
> > 
> > How are you?
> > 
> > Just making sure- you sent those as updates right? I have nothing further
> > to do?
> > 
> > I saw that the new google fonts are up on the new website (NICE website)
> > but didn't see Bellefair there.
> > Do you know why?
> > 
> > I'm asking because there's a buzz in Israel about those new fonts and I
> > would hate to see Bellefair go out of the radar.
> > 
> > Have a lovely day,
> > Liron
> > 
> > On Mon, May 23, 2016 at 5:25 PM, Dave Crossland <
> > notifications@github.com>
> > wrote:
> > 
> > > Closed #3 https://github.com/shinntype/bellefair/issues/3.
> > > 
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/shinntype/bellefair/issues/3#event-669024922
> > 
> > ## 
> > 
> > Liron Lavi Turkenich
> > Type & Graphic Design, Research
> > 
> > +972-544872265
> > www.lironlavi.com
> > @LironLaviTur https://twitter.com/LironLaviTur
> > Aravrit https://www.facebook.com/aravrit?ref=aymt_homepage_panel, one
> > script, two languages
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/shinntype/bellefair/issues/3#issuecomment-226214774,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOgOWSMJmlB24AeRjfg2zYWcqXND8t-_ks5qMBOAgaJpZM4HnoPh
> .

## 

Liron Lavi Turkenich
Type & Graphic Design, Research

+972-544872265
www.lironlavi.com
@LironLaviTur https://twitter.com/LironLaviTur
Aravrit https://www.facebook.com/aravrit?ref=aymt_homepage_panel, one
script, two languages

**Comment by davelab6** [comment]
I guess the new figures would be access via OpenType 'locl' feature? If so
that would be an update that could just 'slip in' later... how quickly do
you think you could make the update? I could potentially delay this update
for 1-2 weeks

**Comment by lironlavitur** [comment]
Mmmm good question. I'm really busy with writing texts for the 365typo book, but I do want to get it done. 
When would you want to release the next batch?

**Comment by davelab6** [comment]
If this would be an OT feature, not a change to the default numbers, then
it wouldn't block the release and you could do the update at any time

**Comment by lironlavitur** [comment]
It would be set as .loclIWR , so while typing Hebrew it will be default.

I will try to work on this ASAP

On Fri, Jun 17, 2016 at 3:28 PM, Dave Crossland notifications@github.com
wrote:

> If this would be an OT feature, not a change to the default numbers, then
> it wouldn't block the release and you could do the update at any time
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/shinntype/bellefair/issues/3#issuecomment-226756317,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOgOWSMFIOKdx0BVjAbN2M_ApjWx3U56ks5qMpL6gaJpZM4HnoPh
> .

## 

Liron Lavi Turkenich
Type & Graphic Design, Research

+972-544872265
www.lironlavi.com
@LironLaviTur https://twitter.com/LironLaviTur
Aravrit https://www.facebook.com/aravrit?ref=aymt_homepage_panel, one
script, two languages
